### PR TITLE
Update to add shadowmask support

### PR DESCRIPTION
**Pull request by Kretin1**
This hasn't been fully tested, but it works in my scenes with shadowmasks. I haven't tested for scenes without shadowmasks so I'm not sure if my checks will work (I couldn't find a way to access the Shadowmask setting directly).

### CODE REVIEW

**Comment by laurenth-unity** [comment]
Thanks a lot for this, I should definitely look into merging it.

**Comment by laurenth-unity** [comment]
I've included the code in the improvements branch. It took me a while because I wanted it to include the loading and unloading of the lighting scene, also applying the shadowmask correctly at runtime required a few tweaks.

**Comment by laurenth-unity** [comment]
shadowmask now in master but done through another branch because of some other changes I wanted to make. Thanks for your contribution 👍

**Comment by laurenth-unity** [comment]
FYI I mentioned you in the readme file in the "contributions" section because I didn't know how to make you appear in contributors.

**Comment by Kretin1** [comment]
Thanks, much appreciated!

**Pull request closed without merging**
